import Head from "next/head";
import Container from "react-bootstrap/Container";
import AppGuides from "@/components/AppGuides";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import ExampleComponents from "@/components/ExampleComponents";
import Hero from "@/components/Hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>Bootstrap w/ React</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container className="px-3 mx-auto">
          <Header />
        </Container>
        {/* <Container className="py-4 px-3 mx-auto"> */}
        <Hero />
        {/* </Container> */}
        <Container className="px-3 mx-auto">
          <Footer />
        </Container>
      </main>
      {/* <Container as="main" className="py-4 px-3 mx-auto">
        <Header />
        <Hero />
        <Footer />
      </Container> */}
    </>
  );
}
